// HU lang variables

tinyMCE.addI18n('hu.advanced',{
style_select:"Stílusok",
font_size:"Betűméret",
fontdefault:"Betűtípus",
block:"Format",
paragraph:"Bekezdés",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Fejléc 1",
h2:"Fejléc 2",
h3:"Fejléc 3",
h4:"Fejléc 4",
h5:"Fejléc 5",
h6:"Fejléc 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Félkövér (Ctrl+B)",
italic_desc:"Dőlt (Ctrl+I)",
underline_desc:"Aláhúzott (Ctrl+U)",
striketrough_desc:"Áthúzott",
justifyleft_desc:"Balra igazít",
justifycenter_desc:"Középre igazít",
justifyright_desc:"Jobbra igazít",
justifyfull_desc:"Sorkizárt",
bullist_desc:"Lista",
numlist_desc:"Számozott lista",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Vissza (Ctrl+Z)",
redo_desc:"Újra (Ctrl+Y)",
link_desc:"Link beszúrása/szerkesztése",
unlink_desc:"Link törlése",
image_desc:"Kép beszúrása/szerkesztése",
cleanup_desc:"Kód megtisztítása",
code_desc:"HTML forrás szerkesztése",
sub_desc:"Alsó index",
sup_desc:"Felső index",
hr_desc:"Elválasztó vonal beszúrása",
removeformat_desc:"Formázás eltávolítása",
custom1_desc:"Your custom description here",
forecolor_desc:"Betűszín",
backcolor_desc:"Háttérszín",
charmap_desc:"Speciális karakter beszúrása",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"Kivágás",
copy_desc:"Másolás",
paste_desc:"Beillesztés",
image_props_desc:"Kép tulajdonságai",
newdocument_desc:"Új dokumentum",
help_desc:"Segítség",
blockquote_desc:"Blockquote",
clipboard_msg:"Másolás, kivágás, beillesztés nem működik Firefoxban és Mozzillában.",
path:"Elérési út",
newdocument:"Biztos benne hogy törli?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"Több szín",
paste_text_desc: "Csak szöveg beillesztése",
paste_word_desc: "Beillesztés Word-ből"
});
